#ifndef TYPES_TOPICIDTYPE_H_
#define TYPES_TOPICIDTYPE_H_

enum TopicIdType {
    NORMAL_TOPIC_ID = 0b00,
    PRE_DEFINED_TOPIC_ID = 0b01,
    SHORT_TOPIC_NAME = 0b10
};

#endif /* TYPES_TOPICIDTYPE_H_ */
